mapping_dict = {
    "Rental Rate": "rental-rate",
    "Rent for Houses": "rent-for-houses",
    "Cap Rate": "cap-rate",
    "Vacancy Rate": "vacancy-rate",
    "Rent as % of Income": "rent-to-income",
    "Shadow Inventory %": "shadow-inventory",
    "Building Permits": "building-permits",
    "Home Value to Rent Ratio": "home-value-to-rent-ratio",
    "Migration Total": "migration-total",
    "Migration % of Population": "migration-to-population",
    "Rent Growth (YoY)": "rent-growth-yoy",
    "Population": "population",
    "Median Household Income": "income",
    "Population Growth": "population-growth",
    "Income Growth": "income-growth",
    "Mortgaged Home %": "mortgaged-home-%",
    "Median Age": "median-age",
    "Homeownership Rate": "homeownership-rate",
    "Poverty Rate": "poverty-rate",
    "Housing Units": "housing-units",
    "Housing Units Growth Rate": "housing-units-growth-rate",
    "College Degree Rate": "college-degree-rate",
    "Remote Work %": "remote-work-%",
    "Home Value": "home-value",
    "Home Value Growth (YoY)": "home-value-growth-yoy",
    "Home Value Growth (MoM)": "home-value-growth-mom",
    "Overvalued %": "overvalued-%",
    "Value Income Ratio": "value-to-income-ratio",
    "Mortgage Payment": "mortgage-payment",
    "Salary to Afford a House": "salary-to-house",
    "Mtg Payment as % of Income": "mtg-payment-to-income",
    "Property Tax Rate": "property-tax-rate",
    "Buy v Rent Differential": "buy-rent-differential",
    "% Crash from 2007-12": "%-crash-07-12",
    "For Sale Inventory": "for-sale-inventory",
    "Sale Inventory Growth": "sale-inventory-growth",
    "Inventory Surplus Deficit": "inventory-surplus-deficit",
    "Price Cut %": "price-cut-%",
    "Days on Market": "days-on-market",
    "Days on Market Growth (YoY)": "days-on-market-growth",
    "Inventory as % of Houses": "inventory-to-houses",
    "Median Listing Price": "median-listing-price",
    "Median Listing Price Growth (YoY)": "median-listing-price-growth-yoy",
    "New Listing Count": "new-listing-count",
    "New Listing Count Growth (YoY)": "new-listing-count-growth-yoy"
}

state_mapping = {
    "01": "AK", "02": "AL", "04": "AR", "05": "AZ", "06": "CA", "08": "CO",
    "09": "CT", "10": "DC", "11": "DE", "12": "FL", "13": "GA", "15": "HI",
    "16": "IA", "17": "ID", "18": "IL", "19": "IN", "20": "KS", "21": "KY",
    "22": "LA", "23": "MA", "24": "MD", "25": "ME", "26": "MI", "27": "MN",
    "28": "MO", "29": "MS", "30": "MT", "31": "NC", "32": "ND", "33": "NE",
    "34": "NH", "35": "NJ", "36": "NM", "37": "NV", "38": "NY", "39": "OH",
    "40": "OK", "41": "OR", "42": "PA", "44": "RI", "45": "SC", "46": "SD",
    "47": "TN", "48": "TX", "49": "UT", "50": "VA", "51": "VT", "53": "WA",
    "54": "WI", "55": "WV", "56": "WY"
}

yoy_list = [
    'college-degree-rate',
    'homeownership-rate',
    'housing-units',
    'housing-units-growth-rate',
    'income',
    'income-growth',
    'median-age',
    'mortgaged-home-%',
    'population',
    'population-growth',
    'poverty-rate',
    'remote-work-%'
]
